import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant'

const navigationConfig = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'catalogue',
        path: '',
        title: 'Catalogue',
        translateKey: 'nav.catalogue',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'catalogue.products',
                path: '/products',
                title: 'Products',
                translateKey: 'nav.products',
                icon: 'product',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'catalogue.categories',
                path: '/categories',
                title: 'Categories',
                translateKey: 'nav.categories',
                icon: 'category',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'site',
        path: '',
        title: 'Website',
        translateKey: 'nav.site',
        icon: 'site',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'site.newsletter',
                path: '/newsletter',
                title: 'Newsletter',
                translateKey: 'nav.newsletter',
                icon: 'newsletter',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'site.banners',
                path: '/banners',
                title: 'Banners',
                translateKey: 'nav.banners',
                icon: 'banner',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'settings',
        path: '',
        title: 'Settings',
        translateKey: 'nav.settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'settings.warehouses',
                path: '/warehouses',
                title: 'Warehouses',
                translateKey: 'nav.warehouses',
                icon: 'warehouse',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'settings.params',
                path: '/params',
                title: 'Parameters',
                translateKey: 'nav.parameters',
                icon: 'gear',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'settings.countries',
                path: '/countries',
                title: 'Countries',
                translateKey: 'nav.countries',
                icon: 'flag',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'settings.cities',
                path: '/cities',
                title: 'Cities',
                translateKey: 'nav.cities',
                icon: 'city',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'settings.manufacturers',
                path: '/manufacturers',
                title: 'Manufacturers',
                translateKey: 'nav.manufacturers',
                icon: 'manufacturer',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'settings.brands',
                path: '/brands',
                title: 'Brands',
                translateKey: 'nav.brands',
                icon: 'brand',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
