const categoriesFields = [
    {
        field: 'id',
        name: 'Category ID',
        type: 'text',
        description: '',
        placeholder: '',
        inTable: true,
        inForm: true,
        disabled: false,
        sortable: true,
        required: true,
        defaultValue: '',
    },
    {
        field: 'name',
        name: 'Naziv',
        type: 'text',
        description: '',
        placeholder: '',
        inTable: true,
        inForm: true,
        disabled: false,
        sortable: true,
        required: true,
        defaultValue: '',
    },
    {
        field: 'description',
        name: 'Opis',
        type: 'textarea',
        description: '',
        placeholder: '',
        inTable: true,
        inForm: true,
        disabled: false,
        sortable: true,
        required: true,
        defaultValue: '',
    },
]

export default categoriesFields
